In [10]:
import csv
from datetime import datetime

#. 파일을 읽습니다.
file = open("D:\data\경상남도_통영시_통영시립욕지도서관보유도서목록현황_20230208.csv", 
            'r',
           encoding = 'UTF-8')

#. csv 라이브러리가  csv 파일을 읽을 수 있도록 변환합니다.
reader = csv.reader(file)

# 도서관명, 등록번호, 자료명, 저자명, 발행처,발행연도,관리기관명, 데이터기준일자

is_header = True
books = []
datetime_format = "%Y-%m-%d"

for line in reader:
    if is_header == True:
        is_header = False
        continue
    
    if len(line) < 8 :
        continue
        
    book = {
        "library_name" : line[0], 
        "book_number": int(line[1]), 
        "book_name": line[2],
        "author" : line[3],
        "publisher": line[4],
        "publish_year": line[5],
        "sido" : line[6],
        "create_date": datetime.strptime(line[7], datetime_format)
    }
    books.append(book)
    
len(books)

50753

In [19]:
import pymongo
import pandas as pd

# Mongodb와 연결합니다.
client = pymongo.MongoClient("mongodb://localhost:27017")

collection = client['test']['books']

# 대량의 데이터를  Insert 한다. insert_many
# print("--------------------------------- START ------------------------")
# collection.insert_many(books)
# print("--------------------------------- END ---------------------------")
datas = list(collection.find().limit(10))

datas = pd.DataFrame(datas)

datas

,_id,library_name,book_number,book_name,author,publisher,publish_year,sido,create_date
0,63e5e02be0ffba6ec86ff10c,통영시립욕지도서관,1,노자익,焦횡弱侯 집 이현주 역,두레,2000,경상남도 통영시 욕지면,2023-02-08
1,63e5e02be0ffba6ec86ff10d,통영시립욕지도서관,2,논어,박정수 엮음,청목사,2001,경상남도 통영시 욕지면,2023-02-08
2,63e5e02be0ffba6ec86ff10e,통영시립욕지도서관,3,표류공주 1,최후식 저,시공사,2000,경상남도 통영시 욕지면,2023-02-08
3,63e5e02be0ffba6ec86ff10f,통영시립욕지도서관,4,표류공주 2,최후식 저,시공사,2000,경상남도 통영시 욕지면,2023-02-08
4,63e5e02be0ffba6ec86ff110,통영시립욕지도서관,5,표류공주 3,최후식 저,시공사,2000,경상남도 통영시 욕지면,2023-02-08
5,63e5e02be0ffba6ec86ff111,통영시립욕지도서관,6,표류공주 4,최후식 저,시공사,2000,경상남도 통영시 욕지면,2023-02-08
6,63e5e02be0ffba6ec86ff112,통영시립욕지도서관,7,三國志 1 도원에 피는 의,나관중 지음 이문열 평역,민음사,2000,경상남도 통영시 욕지면,2023-02-08
7,63e5e02be0ffba6ec86ff113,통영시립욕지도서관,8,三國志 2 구름처럼이는영웅,나관중 지음 이문열 평역,민음사,2001,경상남도 통영시 욕지면,2023-02-08
8,63e5e02be0ffba6ec86ff114,통영시립욕지도서관,9,三國志 3 헝클어진 천하,나관중 지음 이문열 평역,민음사,2001,경상남도 통영시 욕지면,2023-02-08
9,63e5e02be0ffba6ec86ff115,통영시립욕지도서관,10,三國志 4 칼한자루 말한필로천리를닫다,나관중 지음 이문열 평역,민음사,2001,경상남도 통영시 욕지면,2023-02-08

In [20]:
import pymongo
import pandas as pd

# Mongodb와 연결합니다.
client = pymongo.MongoClient("mongodb://localhost:27017")

collection = client['test']['books']
datas = list(collection.find({ "author" : "" }))

datas = pd.DataFrame(datas)

datas

,_id,library_name,book_number,book_name,author,publisher,publish_year,sido,create_date
0,63e5e02be0ffba6ec86ff305,통영시립욕지도서관,509,얼음과 불의 노래 1 2부 왕들의 전쟁,,은행나무,2001,경상남도 통영시 욕지면,2023-02-08
1,63e5e02be0ffba6ec86ff306,통영시립욕지도서관,510,얼음과 불의 노래 2 왕좌의 게임,,은행나무,2001,경상남도 통영시 욕지면,2023-02-08
2,63e5e02be0ffba6ec86ff5d9,통영시립욕지도서관,1233,여성의 몸 여성의 나이,,또하나의 문화,2001,경상남도 통영시 욕지면,2023-02-08
3,63e5e02be0ffba6ec86ff5eb,통영시립욕지도서관,1251,런던,,서울문화사,2000,경상남도 통영시 욕지면,2023-02-08
4,63e5e02be0ffba6ec86ff5ec,통영시립욕지도서관,1252,이칼리아,,서울문화사,2000,경상남도 통영시 욕지면,2023-02-08
...,...,...,...,...,...,...,...,...,...
137,63e5e02be0ffba6ec8707d37,통영시립욕지도서관,36016,달라서 좋아요!,,대교출판,2006,경상남도 통영시 욕지면,2023-02-08
138,63e5e02be0ffba6ec8707e08,통영시립욕지도서관,36225,짝꿍 바꿔 주세요,,주니어랜덤,2006,경상남도 통영시 욕지면,2023-02-08
139,63e5e02be0ffba6ec8707e0a,통영시립욕지도서관,36227,그림이 말을 거는 생각미술관,,길벗어린이,2006,경상남도 통영시 욕지면,2023-02-08
140,63e5e02be0ffba6ec8707e2d,통영시립욕지도서관,36262,봉선화가 필 무렵 윤정모 역사동화,,푸른나무,2006,경상남도 통영시 욕지면,2023-02-08
141,63e5e02be0ffba6ec8707e64,통영시립욕지도서관,36317,섬에 온 쌍둥이 별 박종현 환상동화,,세계문예,2006,경상남도 통영시 욕지면,2023-02-08