In [1]:
import csv
from datetime import datetime

#. 파일을 읽습니다.
file = open("D:\data\경상남도 통영시_꿈이랑도서관보유도서목록현황_20230206.csv", 
            'r',
           encoding = 'UTF-8')

#. csv 라이브러리가  csv 파일을 읽을 수 있도록 변환합니다.
reader = csv.reader(file)

# 도서관명, 등록번호, 자료명, 저자명, 발행처,발행연도,관리기관명, 데이터기준일자

is_header = True
books = []
datetime_format = "%Y-%m-%d"

for line in reader:
    if is_header == True:
        is_header = False
        continue
    
    if len(line) < 8 :
        continue
        
    book = {
        "library_name" : line[0], 
        "book_number": line[1], 
        "book_name": line[2],
        "author" : line[3],
        "publisher": line[4],
        "publish_year": line[5],
        "sido" : line[6],
        "create_date": datetime.strptime(line[7], datetime_format)
    }
    books.append(book)
    
len(books)

34850

In [3]:
import pymongo
import pandas as pd

# Mongodb와 연결합니다.
client = pymongo.MongoClient("mongodb://localhost:27017")

collection = client['test']['books']

# 대량의 데이터를  Insert 한다. insert_many
#print("--------------------------------- START ------------------------")
#collection.insert_many(books)
#print("--------------------------------- END ---------------------------")
datas = list(collection.find({"library_name" : "꿈이랑도서관"}).limit(10))

datas = pd.DataFrame(datas)

datas

,_id,library_name,book_number,book_name,author,publisher,publish_year,sido,create_date
0,63e5efea5721ad3dd4ecf4cd,꿈이랑도서관,EM0000000060,어린이 시사마당 : 문화.스포츠 편,우리누리 저;윤정주,중앙일보사,1995,경상남도 통영시 평생학습관,2023-02-06
1,63e5efea5721ad3dd4ecf4ce,꿈이랑도서관,EM0000000062,어린이 시사마당 : 세계사사.국제관계 편,우리누리 저;윤정주,중앙일보사,1995,경상남도 통영시 평생학습관,2023-02-06
2,63e5efea5721ad3dd4ecf4cf,꿈이랑도서관,EM0000000092,역사박사 논리천재 : 고려시대(1),에이스논리연구원 저;권태원 그림.,신원문화사,1996 .,경상남도 통영시 평생학습관,2023-02-06
3,63e5efea5721ad3dd4ecf4d0,꿈이랑도서관,EM0000000093,역사박사 논리박사 : 고려시대(1),에이스논리연구원 저;권태원 그림.,신원문화사,1996 .,경상남도 통영시 평생학습관,2023-02-06
4,63e5efea5721ad3dd4ecf4d1,꿈이랑도서관,EM0000000102,우리 작가 새 동화 : 아침에 부르는 자장가네,김병규 저;심미아 그림.,중앙일보사,1995 .,경상남도 통영시 평생학습관,2023-02-06
5,63e5efea5721ad3dd4ecf4d2,꿈이랑도서관,EM0000000149,소중한 우리 것 재미난 우리 얘기 : 나라를 지킨 호랑이 장군들,우리 누리 저;전병준 그림.,중앙일보사,1995,경상남도 통영시 평생학습관,2023-02-06
6,63e5efea5721ad3dd4ecf4d3,꿈이랑도서관,EM0000000151,소중한 우리 것 재미난 우리 얘기 : 신나는 열두 달 명절이야기,우리 누리 저;권사우 그림.,중앙일보사,1995,경상남도 통영시 평생학습관,2023-02-06
7,63e5efea5721ad3dd4ecf4d4,꿈이랑도서관,EM0000000169,세상에서 가장 큰 동물 이야기,지니 존슨 저;마이클 우즈 그림.,중앙일보사,1997,경상남도 통영시 평생학습관,2023-02-06
8,63e5efea5721ad3dd4ecf4d5,꿈이랑도서관,EM0000000171,세상에서 가장 빠른 동물 이야기,지니 존슨 저;튜터 험프리스 그림.,중앙일보사,1997,경상남도 통영시 평생학습관,2023-02-06
9,63e5efea5721ad3dd4ecf4d6,꿈이랑도서관,EM0000000189,셰익스피어의 4대비극,윌리엄 셰익스피어 저;편집부 역음.,작은평화,1994,경상남도 통영시 평생학습관,2023-02-06

In [20]:
import pymongo
import pandas as pd

# Mongodb와 연결합니다.
client = pymongo.MongoClient("mongodb://localhost:27017")

collection = client['test']['books']
datas = list(collection.find({ "author" : "" }))

datas = pd.DataFrame(datas)

datas

,_id,library_name,book_number,book_name,author,publisher,publish_year,sido,create_date
0,63e5e02be0ffba6ec86ff305,통영시립욕지도서관,509,얼음과 불의 노래 1 2부 왕들의 전쟁,,은행나무,2001,경상남도 통영시 욕지면,2023-02-08
1,63e5e02be0ffba6ec86ff306,통영시립욕지도서관,510,얼음과 불의 노래 2 왕좌의 게임,,은행나무,2001,경상남도 통영시 욕지면,2023-02-08
2,63e5e02be0ffba6ec86ff5d9,통영시립욕지도서관,1233,여성의 몸 여성의 나이,,또하나의 문화,2001,경상남도 통영시 욕지면,2023-02-08
3,63e5e02be0ffba6ec86ff5eb,통영시립욕지도서관,1251,런던,,서울문화사,2000,경상남도 통영시 욕지면,2023-02-08
4,63e5e02be0ffba6ec86ff5ec,통영시립욕지도서관,1252,이칼리아,,서울문화사,2000,경상남도 통영시 욕지면,2023-02-08
...,...,...,...,...,...,...,...,...,...
137,63e5e02be0ffba6ec8707d37,통영시립욕지도서관,36016,달라서 좋아요!,,대교출판,2006,경상남도 통영시 욕지면,2023-02-08
138,63e5e02be0ffba6ec8707e08,통영시립욕지도서관,36225,짝꿍 바꿔 주세요,,주니어랜덤,2006,경상남도 통영시 욕지면,2023-02-08
139,63e5e02be0ffba6ec8707e0a,통영시립욕지도서관,36227,그림이 말을 거는 생각미술관,,길벗어린이,2006,경상남도 통영시 욕지면,2023-02-08
140,63e5e02be0ffba6ec8707e2d,통영시립욕지도서관,36262,봉선화가 필 무렵 윤정모 역사동화,,푸른나무,2006,경상남도 통영시 욕지면,2023-02-08
141,63e5e02be0ffba6ec8707e64,통영시립욕지도서관,36317,섬에 온 쌍둥이 별 박종현 환상동화,,세계문예,2006,경상남도 통영시 욕지면,2023-02-08